server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
    api-key: secret123
