spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/products_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
product:
  service:
    url: http://product-service:8080/products/